# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
      default-property-inclusion: non_null

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800

#logging:
#  level:
#    org.springframework:
#      security: DEBUG