# noinspection SqlNoDataSourceInspectionForFile
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (1, 'admin', '$2a$10$rj9Hq.12GVArqiOJbOZNpuFq5IupVh2RrOGwYgAcMUbz/jNvS7gqu', 'admin', 'admin', 'admin@admin.com', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (2, 'user', '$2a$10$rj9Hq.12GVArqiOJbOZNpuFq5IupVh2RrOGwYgAcMUbz/jNvS7gqu', 'user', 'user', 'enabled@user.com', 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (3, 'disabled', '$2a$10$rj9Hq.12GVArqiOJbOZNpuFq5IupVh2RrOGwYgAcMUbz/jNvS7gqu', 'user', 'user', 'disabled@user.com', 0, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);


INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (1, '标题1','内容1',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (2, '标题2','内容2',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (3, '标题3','内容3',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (4, '标题4','内容4',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (5, '标题5','内容5',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (6, '标题6','内容6',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (7, '标题7','内容7',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (8, '标题8','内容8',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (9, '标题9','内容9',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (10, '标题10','内容10',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (11, '标题11','内容11',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ARTICLE (ID, TITLE,CONTENT,CREATE_DATE) VALUES (12, '标题12','内容12',PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));